In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [5]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
df = df.drop(columns=['who','deck','alive'])
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,True,Southampton,False
1,1,1,female,38.0,1,0,71.2833,C,First,False,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,S,Third,False,Southampton,True
3,1,1,female,35.0,1,0,53.1000,S,First,False,Southampton,False
4,0,3,male,35.0,0,0,8.0500,S,Third,True,Southampton,True

In [11]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

cols = ['sex','embarked','class','adult_male','embark_town','alone']

for col in cols:
  df[col] = lb.fit_transform(df[col])

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,embark_town,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,2,0
1,1,1,0,38.0,1,0,71.2833,0,0,0,0,0
2,1,3,0,26.0,0,0,7.9250,2,2,0,2,1
3,1,1,0,35.0,1,0,53.1000,2,0,0,2,0
4,0,3,1,35.0,0,0,8.0500,2,2,1,2,1

In [17]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,embark_town,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,2,0
1,1,1,0,38.0,1,0,71.2833,0,0,0,0,0
2,1,3,0,26.0,0,0,7.9250,2,2,0,2,1
3,1,1,0,35.0,1,0,53.1000,2,0,0,2,0
4,0,3,1,35.0,0,0,8.0500,2,2,1,2,1

In [19]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

newCols = [ 'pclass',  'age', 'sibsp', 'parch', 'fare','embarked', 'class',  'embark_town']

for col in newCols:
  df[col] = scaler.fit_transform(df[[col]])

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,embark_town,alone
0,0,0.827377,1,-0.530377,0.432793,-0.473674,-0.502445,0.581114,0.827377,1,0.581114,0
1,1,-1.566107,0,0.571831,0.432793,-0.473674,0.786845,-1.938460,-1.566107,0,-1.938460,0
2,1,0.827377,0,-0.254825,-0.474545,-0.473674,-0.488854,0.581114,0.827377,0,0.581114,1
3,1,-1.566107,0,0.365167,0.432793,-0.473674,0.420730,0.581114,-1.566107,0,0.581114,0
4,0,0.827377,1,0.365167,-0.474545,-0.473674,-0.486337,0.581114,0.827377,1,0.581114,1

In [37]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         0
class            0
adult_male       0
embark_town      0
alone            0
dtype: int64

In [38]:
df['age'] = df['age'].fillna(df['age'].mean())

In [39]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
adult_male     0
embark_town    0
alone          0
dtype: int64

In [40]:
Cleaned_df = df.copy()
Cleaned_df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,embark_town,alone
0,0,0.827377,1,-0.530377,0.432793,-0.473674,-0.502445,0.581114,0.827377,1,0.581114,0
1,1,-1.566107,0,0.571831,0.432793,-0.473674,0.786845,-1.938460,-1.566107,0,-1.938460,0
2,1,0.827377,0,-0.254825,-0.474545,-0.473674,-0.488854,0.581114,0.827377,0,0.581114,1
3,1,-1.566107,0,0.365167,0.432793,-0.473674,0.420730,0.581114,-1.566107,0,0.581114,0
4,0,0.827377,1,0.365167,-0.474545,-0.473674,-0.486337,0.581114,0.827377,1,0.581114,1

In [41]:
X = Cleaned_df.drop(columns=['survived'])
Y = Cleaned_df['survived']

In [42]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.20,random_state=45)

In [52]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

model.fit(X_train,Y_train)

GaussianNB()

In [53]:
Y_pred = model.predict(X_test)

In [44]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [54]:
acc = accuracy_score(Y_test,Y_pred)
acc

0.8156424581005587

In [55]:
matrix = confusion_matrix(Y_test,Y_pred)
matrix

array([[96, 21],
       [12, 50]])

In [56]:
report = classification_report(Y_test,Y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.89      0.82      0.85       117
           1       0.70      0.81      0.75        62

    accuracy                           0.82       179
   macro avg       0.80      0.81      0.80       179
weighted avg       0.82      0.82      0.82       179