In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [4]:
df = pd.read_csv("movies_metadata.csv")
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [5]:
df.shape

(45466, 24)

In [6]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [7]:
df = df[['title','overview','tagline','genres','vote_count','popularity']]
df.head()

,title,overview,tagline,genres,vote_count,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",NaN,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",5415.0,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",2413.0,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",92.0,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",34.0,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,"[{'id': 35, 'name': 'Comedy'}]",173.0,8.387519

In [8]:
df.isnull().sum()

title             6
overview        954
tagline       25054
genres            0
vote_count        6
popularity        5
dtype: int64

In [9]:
df['title'] = df['title'].fillna("")
df['tagline'] = df['tagline'].fillna("")
df['overview'] = df['overview'].fillna("")

In [10]:
df['genres'][0]

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [11]:
import ast

df['genres'] = df['genres'].apply(
    lambda x: " ".join(i['name'] for i in ast.literal_eval(x))
)
df['genres']

0         Animation Comedy Family
1        Adventure Fantasy Family
2                  Romance Comedy
3            Comedy Drama Romance
4                          Comedy
                   ...
45461                Drama Family
45462                       Drama
45463       Action Drama Thriller
45464
45465
Name: genres, Length: 45466, dtype: object

In [12]:
df.head()

,title,overview,tagline,genres,vote_count,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",,Animation Comedy Family,5415.0,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,Adventure Fantasy Family,2413.0,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,Romance Comedy,92.0,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,Comedy Drama Romance,34.0,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,Comedy,173.0,8.387519

In [13]:
df['tags'] = df['title'] + " " + df['overview'] + " " + df['tagline'] + " " + df['genres']

In [14]:
df['tags'][1]

"Jumanji When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Roll the dice and unleash the excitement! Adventure Fantasy Family"

In [15]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

nltk.download('punkt_tab')
nltk.download('wordnet')
nltk.download("stopwords")

lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [16]:
words = word_tokenize(df['tags'][0])
a = [lemmatizer.lemmatize(word.lower(),pos='v') for word in words if word.lower() not in stopwords.words('english')]
a = " ".join(a)
a

"toy story lead woody , andy 's toy live happily room andy 's birthday bring buzz lightyear onto scene . afraid lose place andy 's heart , woody plot buzz . circumstances separate buzz woody owner , duo eventually learn put aside differences . animation comedy family"

In [17]:
b = df.copy()

In [18]:
df['tags'] = df['tags'].apply(
    lambda text: " ".join([lemmatizer.lemmatize(word.lower(),pos='v') for word in word_tokenize(text) if word.lower() not in stopwords.words('english')])
)

In [19]:
df['tags'][1]

"jumanji siblings judy peter discover enchant board game open door magical world , unwittingly invite alan -- adult 's trap inside game 26 years -- live room . alan 's hope freedom finish game , prove risky three find run giant rhinoceroses , evil monkey terrify creatures . roll dice unleash excitement ! adventure fantasy family"

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

vectors = tfidf.fit_transform(df['tags'])
vectors

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1264623 stored elements and shape (45466, 5000)>

In [21]:
from sklearn.metrics.pairwise import cosine_similarity

In [22]:
df = df.reset_index(drop=True)

In [63]:
df['title'] = df['title'].apply(
    lambda tit:  tit.lower()
)

In [65]:
indices =pd.Series(df.index,index=df['title']).drop_duplicates()
indices

title
toy story                          0
jumanji                            1
grumpier old men                   2
waiting to exhale                  3
father of the bride part ii        4
                               ...
subdue                         45461
century of birthing            45462
betrayal                       45463
satan triumphant               45464
queerama                       45465
Length: 45466, dtype: int64

In [67]:
def recommedation(title,max_size=10):
  title = title.lower()
  if title not in indices:
     return ["Movie not found"]
  idx = indices[title]
  sim_score = cosine_similarity(vectors[idx],vectors).flatten()
  similar_idx = sim_score.argsort()[::-1][1:max_size+1]
  return df['title'].iloc[similar_idx]

In [75]:
recommedation('toy story')

15348                                     toy story 3
2997                                      toy story 2
38476    superstar: the life and times of andy warhol
43427                andy kaufman plays carnegie hall
8327                                        the champ
23843                     andy hardy's blonde trouble
10301                          the 40 year old virgin
3057                                  man on the moon
42721    andy peters: exclamation mark question point
35286         raggedy ann & andy: a musical adventure
Name: title, dtype: object